### ISSUE TITLE
npm install doesn't work in my env

### ISSUE THREAD

**Issue by RickyShiJs** [yoyow-org/yoyow-node-sdk#1]
run: 
 npm install

Log as below:

839 silly pacote range manifest for babel-preset-es2015@^6.24.1 fetched in 2ms
840 silly resolveWithNewModule babel-preset-es2015@6.24.1 checking installable status
841 http fetch GET 200 https://registry.npmjs.org/nodemon 3ms (from cache)
842 silly pacote range manifest for babel-preset-stage-2@^6.24.1 fetched in 8ms
843 silly resolveWithNewModule babel-preset-stage-2@6.24.1 checking installable status
844 silly fetchPackageMetaData error for nodemon@^1.11.0 Unexpected end of input at 1:15995
844 silly fetchPackageMetaData "nodemon":"./nodemon.js"},"directories":{},"dist":{"shasum":"c0667a00
844 silly fetchPackageMetaData                                                                      ^
845 verbose stack SyntaxError: Unexpected end of input at 1:15995
845 verbose stack "nodemon":"./nodemon.js"},"directories":{},"dist":{"shasum":"c0667a00
845 verbose stack                                                                      ^
845 verbose stack     at Object.parseJSON (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-helpfulerror/node_modules/jju/lib/parse.js:745:13)
845 verbose stack     at parse (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-helpfulerror/index.js:10:13)
845 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
845 verbose stack     at <anonymous>
845 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
846 verbose cwd /Users/ruiqi.shi/yoyow-node-sdk/examples/yoyow-authorize
847 verbose Darwin 16.7.0
848 verbose argv "/usr/local/Cellar/node/8.2.1/bin/node" "/usr/local/bin/npm" "install"
849 verbose node v8.2.1
850 verbose npm  v5.3.0
851 error Unexpected end of input at 1:15995
851 error "nodemon":"./nodemon.js"},"directories":{},"dist":{"shasum":"c0667a00
851 error                                                                      ^
852 verbose exit [ 1, true ]

**Comment by xiangxn** [comment]
Did you forget "npm install -g nodemon"？
