### ISSUE TITLE
Dockerfile 问题

### ISSUE THREAD

**Issue by 1522402210** [yoyow-org/yoyow-node-sdk#26]
@ety001 
Dockerfile，映射出来的端口与官方例子不统一，应该是3000端口，请修改。

另外，文件夹权限也有问题，请修改。

![image](https://user-images.githubusercontent.com/25600994/41900031-56b742fa-7960-11e8-9e6c-d12636473574.png)

![image](https://user-images.githubusercontent.com/25600994/41900049-626eb4a2-7960-11e8-8076-fb1cdfaab819.png)

请修正，谢谢

**Comment by ety001** [comment]
@1522402210 端口问题我发现了，但是启动代码里的就是3001，所以我的dockerfile也跟代码保持了一致，而不是跟文档保持一致。

403的问题，应该是你当前访问的IP未加入allow_ip中，所以没有权限访问。如果你是linux的话，把你当前测试用的机器的局域网ip加入到 config.js 的 allow_ip 中就可以了。如果是 mac 的话，把容器所在网段的网关地址加入到 allow_ip 中。

**Comment by ety001** [comment]
@1522402210 漏掉一点，修改 config.js 后，需要重启下容器才能生效。
